### ISSUE TITLE
Yolov3

### ISSUE THREAD

**Issue by kyeshmz** [TetsuakiBaba/ofxYolov2#2]
Hello,

Wondering if we could implement Yolo v3 with this build, I see that you were trying to make some of the configurations. 
Maybe something like this 
https://github.com/opencv/opencv/issues/11310

I saw in some of the code that you were trying it out, let me know if you had any plans. 
Thanks,

**Comment by TetsuakiBaba** [comment]
OpenCV officially supports Yolo v.3 on the version of 3.4.3 or upper. Now, homebrew updated OpenCV version 3.4.3. I did not confirm by myself, it might be work by just exchange the cfg and weights files.

Anyway, I'm using local compiled version of 3.4.3 and merged ofxYolov2 and ofxYolov3 and ofxMobileNetSSD to ofxOpenCvDnnObjectDetection which supports yolo, ssd on a simple same code.

I'm going to release this repository soon. 
Best.

**Comment by kyeshmz** [comment]
Sounds great! 
Would also love to merge a local addon version I am working on right now that supports maskrcnn on opencv with accordance to code like here https://qiita.com/miyamotok0105/items/ddeca916df9104fb15bb

Hope to see it soon!

**Comment by TetsuakiBaba** [comment]
Nice work, these kind of segmentation technique needs the resource to run. Here is my simple memo for opencv segmentation. hoping help you ;-)
http://ws.tetsuakibaba.jp/doku.php?id=opencv_dnn:segmentation
